CREATE DATABASE EMPLOYEE

USE EMPLOYEE

CREATE TABLE EMPLOYEE (

	id INT NOT NULL,
    age INT NOT NULL,
    first VARCHAR(225),
    last VARCHAR(225),
    PRIMARY KEY (id)
);

INSERT INTO EMPLOYEE VALUES (100, 18, 'ZARA', 'Ali');
INSERT INTO EMPLOYEE VALUES (101, 19, 'SARA', 'HASSAN');
INSERT INTO EMPLOYEE VALUES (102, 28, 'MOHAMMAD', 'HUSSAIN');
INSERT INTO EMPLOYEE VALUES (103, 38, 'UMER', 'BUTT');
INSERT INTO EMPLOYEE VALUES (104, 14, 'ISHTIAQ', 'ILYAS');

SELECT * FROM EMPLOYEE;